cameras:
  # define cameras using `framegrab` syntax
  - name: back-alley-rtsp
    type: rtsp
    url: rtsp://admin:admin@192.168.1.55:554

detectors:
  - name: dumpster-overflowing
    modality: binary
    query: "Is the dumpster overflowing?"

control:
  - name: dumpster-overflowing
    camera: back-alley-rtsp
    detector: dumpster-overflowing
    poll:
        every: 60 sec
    motion-detection:
        enabled: True

triggers:
  - name: text me if the dumpster is too full
    control-loop: dumpster-overflowing
    action: send-sms
    condition:
        value: YES
        trigger-type: after-n-seconds
        delay: 15 min

actions:
  - name: send-sms
    type: sms
    to: 206-555-5555
    message: "The dumpster is overflowing!"
    limit:
        not-more-than: 1 hr
