name: auto-format
on: pull_request
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
      CODE_PATHS: "src tests"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: chartboost/ruff-action@v1
        with:
          src: ${{ env.CODE_PATHS }}
          args: --profile black
        # Run ruff before black so that black has the final say in formatting.
      - name: run black to auto-format python code
        uses: psf/black@23.1.0
        with:
          src: ${{ env.CODE_PATHS }}
          options: "--verbose --line-length 120"
      - name: Check for modified files
        id: git-check
        run: |
          if git diff-index --quiet HEAD --; then 
            echo "modified=false" >> $GITHUB_ENV
          else 
            echo "modified=true" >> $GITHUB_ENV
          fi
      - name: Push changes
        if: env.modified == 'true'
        run: |
          git config --global user.name 'Auto-format Bot'
          git config --global user.email 'robocoder@groundlight.ai'
          git remote set-url origin https://x-access-token:${{ secrets.ROBOCODER_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automatically reformatting code with black and ruff"
          git push
